configfile: "../config/config.fix.yaml"

print(config)
## singularity container
container: "/scratch/group/lilab/Phil/RNASeq_container.sif"

## include modules
# softlink rawdata 
include: "rules/preprocess.smk"

# rawdata quality control
include: "rules/qc.smk"

# mapping to reference genome
include: "rules/align.smk"

# gene expression quantification
include: "rules/quant.smk"

# raw readcount normalization, sample correlation, PCA
include: "rules/normalize.smk"

# differential gene expression
include: "rules/dge.smk"

# plot venn diagram
include: "rules/venn.smk"

# go enrichment analysis
include: "rules/go.smk"

rule all:
    input:
        get_final_output()