### Required parameters

## Sample information

#samples:
#  sample_name
#  read1: read1_path
#  read2: read2_path
#  group: group_name_this_sample_belongs_to

samples:
  d1_grp_h1:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_grp_h1/d1_grp_h1_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_grp_h1/d1_grp_h1_2.fq.gz
    group: d1_grp_h
  d1_grp_h2:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_grp_h2/d1_grp_h2_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_grp_h2/d1_grp_h2_2.fq.gz
    group: d1_grp_h
  d1_grp_h3:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_grp_h3/d1_grp_h3_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_grp_h3/d1_grp_h3_2.fq.gz
    group: d1_grp_h
  d1_iso_h1:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_iso_h1/d1_iso_h1_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_iso_h1/d1_iso_h1_2.fq.gz
    group: d1_iso_h
  d1_iso_h2:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_iso_h2/d1_iso_h2_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_iso_h2/d1_iso_h2_2.fq.gz
    group: d1_iso_h
  d1_iso_h3:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_iso_h3/d1_iso_h3_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d1_iso_h3/d1_iso_h3_2.fq.gz
    group: d1_iso_h
  d7_grp_h1:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_grp_h1/d7_grp_h1_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_grp_h1/d7_grp_h1_2.fq.gz
    group: d7_grp_h
  d7_grp_h2:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_grp_h2/d7_grp_h2_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_grp_h2/d7_grp_h2_2.fq.gz
    group: d7_grp_h
  d7_grp_h3:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_grp_h3/d7_grp_h3_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_grp_h3/d7_grp_h3_2.fq.gz
    group: d7_grp_h
  d7_iso_h1:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_iso_h1/d7_iso_h1_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_iso_h1/d7_iso_h1_2.fq.gz
    group: d7_iso_h
  d7_iso_h2:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_iso_h2/d7_iso_h2_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_iso_h2/d7_iso_h2_2.fq.gz
    group: d7_iso_h
  d7_iso_h3:
    read1: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_iso_h3/d7_iso_h3_1.fq.gz
    read2: /scratch/group/lilab/Lilab_Seq_Data/250107_novogene_RNAseq/d7_iso_h3/d7_iso_h3_2.fq.gz
    group: d7_iso_h


### Optional parameters
## Correlation heatmap between samples

#corr:
#  plot_title: group1,group2,...

#corr: 
#  all: d1_grp_h,d7_grp_h,d1_iso_h,d7_iso_h

## PCA analysis

#pca_color:
#  color_schema:
#    color_group1: group,group,...
#    color_group2: group,group,...
#    ...

pca_color: 
  day:
    day1: d1_grp_h,d1_iso_h
    day7: d7_grp_h,d7_iso_h
  tisstrt:
    headgrp: d1_grp_h,d7_grp_h
    headiso: d1_iso_h,d7_iso_h

## Differential gene expression

#diff_comparisons:
#  - treatment_vs_control
#  - treatment_vs_control
#  ...

diff_comparisons: []
#  - d7_grp_h_vs_d1_grp_h
#  - d7_iso_h_vs_d1_iso_h
#  - d7_iso_h_vs_d7_grp_h
#  - d1_iso_h_vs_d1_grp_h

## Venn diagram between differential gene expression comparisons

#venn:
#  venn_plot_title: comparison1,comparison2,... (no more than 4 four comparisons)

venn: {}
#  day7_head: d7_grp_h_vs_d1_grp_h,d7_iso_h_vs_d1_iso_h
#  iso_head: d7_iso_h_vs_d1_iso_h,d1_iso_h_vs_d1_grp_h

## GO enrichment of differential expressed gene lists
#GO:
#  - comparison1
#  - comparison2

GO: []
#  - d7_iso_h_vs_d7_grp_h
#  - d1_iso_h_vs_d1_grp_h

### Genome reference used
genome:
  index: /scratch/group/lilab/Genome_Reference/dmel_r6.55/dmel_r6.55
  annotation: /scratch/group/lilab/Genome_Reference/dmel_r6.55/dmel-all-r6.55.gtf
  splicesites: /scratch/group/lilab/Genome_Reference/dmel_r6.55/dmel-all-r6.55.hisat2.splice_sites
  geneloc: /scratch/group/lilab/Genome_Reference/dmel_r6.55/gene_annotation.csv
  geneanno: /scratch/group/lilab/Genome_Reference/dmel_r6.55/gene_annotations.tsv

